# Generated by Django 2.2.6 on 2019-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='status',
            field=models.CharField(choices=[('L', 'Laif Off'), ('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='status',
            field=models.CharField(choices=[('L', 'Laif Off'), ('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='status',
            field=models.CharField(choices=[('L', 'Laif Off'), ('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
    ]
