# Generated by Django 2.2.6 on 2019-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chose_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cook',
            name='status',
            field=models.CharField(choices=[('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='status',
            field=models.CharField(choices=[('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='status',
            field=models.CharField(choices=[('N', 'Not Hired'), ('H', 'Hired')], default='N', max_length=2),
        ),
    ]
