# Generated by Django 2.2.6 on 2019-12-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191206_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
