# Generated by Django 2.2.6 on 2019-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191128_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='food_drop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cook',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
