# Generated by Django 2.2.6 on 2019-11-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191128_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=1024)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Manager')),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Resturant'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Resturant'),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='resturant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Resturant'),
        ),
    ]
