# Generated by Django 2.2.6 on 2019-12-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='commission',
        ),
        migrations.AddField(
            model_name='cook',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverer',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_complaint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_complaint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order_food',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Food'),
        ),
        migrations.AddField(
            model_name='order_food',
            name='food_complaint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='supplyorder',
            name='supply_complaint',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Cook'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='food_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Order'),
        ),
        migrations.AlterField(
            model_name='order_food',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplyorder',
            name='supply_rating',
            field=models.FloatField(null=True),
        ),
    ]
